# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A simple CLI application that prints hello world"
  homepage "https://github.com/cybo42/weather-cli"
  version "1.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.2/weather-cli2_Darwin_x86_64.tar.gz"
      sha256 "1c7a6e1c3825d33ab87c4c7367420c733cfaa082e7cc976ee0e7ddd5654abd37"

      def install
        bin.install "weather-cli"
      end
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.2/weather-cli2_Darwin_arm64.tar.gz"
      sha256 "4ad9d5661be02133035dc978f30d0898bf5e32286840432498c3d813ba73e90b"

      def install
        bin.install "weather-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.2/weather-cli2_Linux_x86_64.tar.gz"
        sha256 "10aa2ff1e316a095c8c87e35122b6bef330db936b38e4bb06579003863333a67"

        def install
          bin.install "weather-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.2/weather-cli2_Linux_arm64.tar.gz"
        sha256 "51928f646707fcbf80042397fa199e302979d3e96bbd3ca4c541b631a80ca105"

        def install
          bin.install "weather-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/weather-cli --version"
  end
end
