# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A simple CLI application that prints hello world"
  homepage "https://github.com/cybo42/weather-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.0.0/weather-cli2_Darwin_x86_64.tar.gz"
      sha256 "99f1d4b7b352ed62634c746a369f6e910693e59f1e901dd9ea19fac9c584fb47"

      def install
        bin.install "weather-cli"
      end
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.0.0/weather-cli2_Darwin_arm64.tar.gz"
      sha256 "c5e14c2f744b4be7faba0d97f484ac0b36e1f4b043623582ca92854ed85b4a1e"

      def install
        bin.install "weather-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.0.0/weather-cli2_Linux_x86_64.tar.gz"
        sha256 "f82737dfa05555ad11605f9b4fed82a502506442650d81bde83c747f0ee46543"

        def install
          bin.install "weather-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.0.0/weather-cli2_Linux_arm64.tar.gz"
        sha256 "9ae93c748ecabd9ef674e2a3de7797057d902314bffe7532d52b37dd8fa306b0"

        def install
          bin.install "weather-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/weather-cli --version"
  end
end
